# Generated by Django 5.1.1 on 2024-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="timeformat",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="timezone",
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_format",
            field=models.CharField(default="%Y-%m-%d", max_length=10),
        ),
    ]
