name: daytistics
services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: daytistics_dev
      POSTGRES_USER: daytistics_user
      POSTGRES_PASSWORD: daytistics_pw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://daytistics_user:daytistics_pw@database:5432/daytistics_dev
    depends_on:
      - database

  frontend:
    volumes:
      - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
