name: daytistics
services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: daytisticsdev
      POSTGRES_USER: daytisticsdev
      POSTGRES_PASSWORD: daytisticsdev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_NAME=daytisticsdev
      - DATABASE_USER=daytisticsdev
      - DATABASE_PASSWORD=daytisticsdev
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
    depends_on:
      - database

  frontend:
    volumes:
      - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
