name: daytistics
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: daytistics_dev
      POSTGRES_USER: daytistics_user
      POSTGRES_PASSWORD: daytistics_pw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - daytistics_network

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://daytistics_user:daytistics_pw@postgres:5432/daytistics_dev
      SECRET_KEY: "Imsupersecret"
    depends_on:
      - postgres
    networks:
      - daytistics_network

  nuxt:
    volumes:
      - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    networks:
      - daytistics_network

  # docs:
  #   volumes:
  #     - ./docs:/app
  #   build:
  #     context: ./docs
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 4000:4000

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - daytistics_network

volumes:
  postgres_data:


networks:
  daytistics_network:
    driver: bridge
