name: daytistics
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    image: python:3.12-slim
    volumes:
      - ./backend:/app
      - ./backend/.venv:/app/.venv
    working_dir: /app
    command: >
      /bin/sh -c "pip install poetry &&
      poetry config virtualenvs.in-project true &&
      poetry install --no-root &&
      poetry run python -Xfrozen_modules=off manage.py runserver 0.0.0.0:8000"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
      DJANGO_SECRET_KEY: "xuh%bc^1%m575%mv@@t87=f6_(i)%c=3jt-+obn&e%=+8qbm!f"
      DJANGO_ALLOWED_HOSTS: "*"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000"
      CSRF_TRUSTED_ORIGINS: "http://localhost:3000"
      CSRF_ALLOWED_ORIGINS: "http://localhost:3000"
      FRONTEND_URL: http://nuxt:3000
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - postgres

  nuxt:
    image: oven/bun:latest
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: >
      /bin/sh -c "bun install &&
      bun run dev --host=0.0.0.0 --port=3000"
    environment:
      API_ADDRESS: http://django:8000
    ports:
      - "3000:3000"
    depends_on:
      - django

volumes:
  postgres_data:
