FROM python:3.12-slim

WORKDIR /app

COPY ./pyproject.toml /app/pyproject.toml

RUN pip install uv

RUN uv sync

COPY ./daytistics /app/daytistics

COPY ./tests /app/tests

EXPOSE 8000

CMD ["uv", "run", "pytest"]