FROM python:3.12-slim

WORKDIR /app

COPY ./pyproject.toml /app/pyproject.toml

RUN pip install uv

RUN uv sync

COPY ./daytistics /app/daytistics

EXPOSE 8000

CMD ["uv", "run", "fastapi", "dev", "daytistics/main.py", "--host", "0.0.0.0", "--port", "8000"]