# Generated by Django 5.1.1 on 2024-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_activityentry_activitytype"),
        ("users", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="activities",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="activities.activitytype"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
