from daytistics.core.settings.base import *

# DJANGO SETTINGS

DEBUG = False


# DEPLOYMENT SETTINGS

SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBmodules = True
SECURE_HSTS_PRELOAD = True

SESSION_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS]
CSRF_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS

# STATIC FILES SETTINGS

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
