contact_links:
  - name: Feature Requests
    url: https://github.com/daytistics/daytistics/discussions/new?category=ideas
    about: Please add any Feature Requests as a Github Discussion using the ideas category.
  - name: Performance, Testing and Documentation Issues
    url: https://github.com/daytistics/daytistics/fork
    about: Create a pull request directly, if this achieves its goal it will be merged
