---

name: Task
description: "MAINTAINER ONLY: Submit a Task that needs to be completed"
title: "⚒️ <Descriptive Title>"
labels: ["⚒️ task"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in Daytistics! 🪴

        Tasks are issues, usually created by maintainers, that are usually used to integrate new features or improve existing ones. Tasks usually arise from discussions in the [ideas channel](https://github.com/orgs/daytistics/discussions/categories/ideas).

        **DO NOT** create a task unless
        - You are a core maintainer who has prior approval via discord/discussions
        - You have otherwise been given approval to post the tasks

        Otherwise, your post will be closed/deleted.

  - type: textarea
    id: summary
    attributes:
      label: Summarize the task briefly and precisely.
      placeholder: Include a brief description of the task including stuff like what it is, what it does, and why it's important.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed/Possible Solution(s)?
      placeholder: Provide as much context around the idea as possible with potential files and roadblocks that may come up.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: Any additional context like links, examples or design ideas.
    validations:
      required: false
