---

name: Task
description: "MAINTAINER ONLY: Submit a Task that needs to be completed"
title: "[TASK] <Descriptive Title>"
labels: ["task"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in Daytistics! 🪴

        This is a place for Daytistics contributors to find tasks that need to get done around the repository. Tasks are different than issues as they are generally related to providing a new feature or improving an existing feature. They are _generally_ not related to an issue. We recommend that you first familiarize yourself with smaller issues in our codebase before starting such a task.

        **DO NOT** create a task unless
        - You are a core maintainer who has prior approval via discord/discussions
        - You have otherwise been given approval to post the tasks

        Otherwise, your post will be closed/deleted.

        **Interested in Taking This?**

        If you're interested in completing this task and it hasn't already been taken, comment below and to let others know you're working on it. As you work through the task, I ask that you submit a draft pull request as soon as possible, and tag this issue so we can all collaborate as best as possible.

  - type: textarea
    id: summary
    attributes:
      label: Summarize the task briefly and precisely.
      placeholder: Include a brief description of the task including stuff like what it is, what it does, and why it's important.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed/Possible Solution(s)?
      placeholder: Provide as much context around the idea as possible with potential files and roadblocks that may come up.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: Any additional context like links, examples or design ideas.
    validations:
      required: false
