# Generated by Django 5.1.1 on 2024-09-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        ("daytistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityentry",
            name="daytistic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_entries",
                to="daytistics.daytistic",
            ),
        ),
        migrations.AddField(
            model_name="activitytype",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="activities.activitycategory",
            ),
        ),
        migrations.AddField(
            model_name="activityentry",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_entries",
                to="activities.activitytype",
            ),
        ),
    ]
