DEFAULT_ACTIVITIES = {
    "physical": [
        "Soccer",
        "Basketball",
        "Volleyball",
        "Tennis",
        "Swimming",
        "Running",
        "Cycling",
        "Yoga",
        "Pilates",
        "Dance",
        "Gymnastics",
        "Martial Arts",
        "Boxing",
        "Climbing",
        "Hiking",
        "Skiing",
        "Snowboarding",
        "Surfing",
        "Skateboarding",
        "Rollerblading",
        "Parkour",
        "Golf",
        "Bowling",
        "Squash",
        "Rowing",
        "Badminton",
    ],
    "mental": [
        "Reading",
        "Puzzles",
        "Chess",
        "Meditation",
        "Learning language",
        "Memory games",
        "Studying",
        "Strategy games",
    ],
    "social": [
        "Meeting friends",
        "Group sports",
        "Participating clubs",
        "Attending events",
        "Volunteering",
        "Team-building",
        "Family gatherings",
        "Game nights",
    ],
    "creative": [
        "Painting",
        "Drawing",
        "Photography",
        "Crafting",
        "Playing instrument",
        "Creative writing",
        "Sculpting",
        "DIY projects",
        "Acting drama",
    ],
    "relaxing": [
        "Meditation",
        "Reading",
        "Watching movies",
        "Listening music",
        "Gardening",
        "Taking baths",
        "Journaling",
        "Spending nature",
    ],
    "educational": [
        "Online courses",
        "Attending lectures",
        "Watching documentaries",
        "Participating workshops",
        "Visiting museums",
        "Researching topics",
        "Writing essays",
    ],
    "adventurous": [
        "Traveling",
        "Exploring places",
        "Camping",
        "Zip-lining",
        "Bungee jumping",
        "Skydiving",
        "Caving",
        "Wildlife safaris",
    ],
    "work": [
        "Working projects",
        "Networking",
        "Skill development",
        "Attending conferences",
        "Team meetings",
        "Mentoring",
        "Freelancing",
    ],
    "household": [
        "Cooking",
        "Cleaning",
        "Organizing",
        "Gardening",
        "DIY improvement",
        "Laundry",
        "Shopping groceries",
        "Home maintenance",
    ],
}
