# Generated by Django 5.0.7 on 2024-08-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytistic',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
