# Generated by Django 5.0.7 on 2024-08-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_daytistic_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityentry',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activityentry',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='daytistic',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='daytistic_activities', to='main.activityentry'),
        ),
    ]
