# Generated by Django 5.0.7 on 2024-08-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_activityentry_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytistic',
            name='activities',
            field=models.ManyToManyField(blank=True, to='main.activityentry'),
        ),
    ]
