# Generated by Django 5.0.7 on 2024-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_daytistic_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytistic',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
