# Generated by Django 5.0.7 on 2024-08-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_daytistic_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityentry',
            name='duration',
            field=models.DurationField(default=None),
        ),
    ]
