"""Update user table (#37)

Revision ID: ca47d946b428
Revises: a405a7f19525
Create Date: 2024-12-11 05:58:40.923302

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca47d946b428'
down_revision: Union[str, None] = 'a405a7f19525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'date_joined')
    op.drop_column('user', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'provider_user_id')
    op.drop_column('user', 'auth_provider')
    # ### end Alembic commands ###
