# Generated by Django 5.1.1 on 2024-09-26 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_activitytype_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activityentry",
            name="daytistic",
        ),
        migrations.AlterField(
            model_name="activityentry",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type",
                to="activities.activitytype",
            ),
        ),
    ]
