# Generated by Django 5.1.1 on 2024-09-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Daytistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "activities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="daytistics",
                        to="activities.activityentry",
                    ),
                ),
                (
                    "diary",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daytistic",
                        to="diary.diaryentry",
                    ),
                ),
            ],
        ),
    ]
