# Generated by Django 5.1.1 on 2024-09-22 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("daytistics", "0001_initial"),
        ("wellbeing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="daytistic",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daytistics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="daytistic",
            name="wellbeings",
            field=models.ManyToManyField(
                blank=True, related_name="daytistics", to="wellbeing.wellbeingentry"
            ),
        ),
    ]
