# Generated by Django 5.1.1 on 2024-10-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daytistics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daytistic",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
