# Generated by Django 5.1.1 on 2024-10-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daytistics", "0003_alter_daytistic_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daytistic",
            name="date",
            field=models.DateField(),
        ),
    ]
