# Generated by Django 5.1 on 2024-08-26 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daytistics", "0002_daytistic_created_at_daytistic_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activityentry",
            name="user",
        ),
        migrations.RemoveField(
            model_name="daytistic",
            name="activities",
        ),
        migrations.AddField(
            model_name="activityentry",
            name="daytistic",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="daytistics.daytistic",
            ),
            preserve_default=False,
        ),
    ]
