# Generated by Django 5.1 on 2024-09-08 08:02

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('daytistics', '0004_daytistic_important'),
	]

	operations = [
		migrations.RemoveField(
			model_name='daytistic',
			name='important',
		),
	]
