# Generated by Django 5.1 on 2024-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daytistics", "0005_remove_daytistic_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="daytistic",
            name="important",
            field=models.BooleanField(default=False),
        ),
    ]
