# Generated by Django 5.1.1 on 2024-09-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_activityentry_activitytype"),
        ("daytistics", "0007_remove_activityentry_activity_and_more"),
        ("users", "0003_alter_customuser_activities_alter_customuser_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.AddField(
            model_name="activityentry",
            name="daytistic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_entries",
                to="daytistics.daytistic",
            ),
        ),
        migrations.AddField(
            model_name="activityentry",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_entries",
                to="activities.activitytype",
            ),
        ),
    ]
