site_name: Daytistics
repo_name: daytistics/daytistics
repo_url: https://github.com/daytistics/daytistics

theme:
  name: material
  favicon: "assets/logo.png"
  logo: "assets/logo.svg"
  language: en
  font:
    code: Roboto markdown_extensions
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: green
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.expand
    - search.highlight
    - dark_mode

nav:
  - Home: "index.md"

  - For Developers:
      - Code of Conduct: "developers/code-of-conduct.md"
      - Become a Contributor: "developers/become-a-contributor.md"
      - Docs & Tutorials:
          - Where are the Docs?: "developers/docs/where-are-the-docs.md"
          - How to Write a Docstring?: "developers/docs/how-to-write-a-docstring.md"

plugins:
  - search
  - social
  - neoteroi.mkdocsoad

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - "styles/extra.css"

extra_javascript:
  - "scripts/extra.js"
