name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build_docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    continue-on-error: true # Allow failure
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MkDocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Build and Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
