name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build_docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build Documentation
        run: |
          cd docs
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/site
