name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pytest:
    name: Backend Integration/Unit Tests
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Dependencies
        run: |
          cd backend
          poetry install --no-root

      - name: Set Up Test Database
        env:
          DJANGO_SETTINGS_MODULE: tests.settings
          DJANGO_SECRET_KEY: "RtcPToOOZ82erjag0zAVAQ3mmha9MrTx"
          DJANGO_ALLOWED_HOSTS: "localhost,example.com"
        run: |
          cd backend
          poetry run python manage.py migrate --noinput

      - name: Run PyTest
        env:
          DJANGO_SETTINGS_MODULE: tests.settings
          DJANGO_SECRET_KEY: "RtcPToOOZ82erjag0zAVAQ3mmha9MrTx"
          DJANGO_ALLOWED_HOSTS: "localhost,example.com"
        run: |
          cd backend
          poetry run pytest

  vitest:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Vitest
        run: |
          cd frontend
          npm vitest --run
